name: ci

on:
    release:
        types: [ created ]

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        env:
            OS: ${{ matrix.os }}
            NODE: '12.x'
        steps:
            - name: Checkout
              uses: actions/checkout@master

            # Setup .npmrc file to publish to GitHub Packages
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - name: Install dependencies
              run: npm ci

            - name: Release
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

