name: ci

on:
    release:
        types: [ created ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            # Setup .npmrc file to publish to GitHub Packages
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x

    publish-npm:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            # Setup .npmrc file to publish to GitHub Packages
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                node-version: 12.x
                registry-url: https://registry.npmjs.org/

            - name: Install dependencies
              run: npm ci

            - name: Release
              run: npm publish
              env:
                NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    publish-gpr:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install dependencies
              uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://npm.pkg.github.com/

            - name: Install dependencies
              run: npm ci

            - name: Release
              run:  npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
