variables:
    SNAPSHOTS_ENABLED: 'false'

include:
    - project: 'hamis/cicd/gitlab/templates/git-flow-ci-yaml'
      ref: '2020.4.2'
      file: 'git-flow.gitlab-ci.yml'

stages:
    - build
    - build-post

build:
    extends: .build
    stage: build
    only:
        - branches
    except:
        - master

publish:
    tags:
        - node
    stage: build-post
    variables:
        RELEASE_VERSION: ${CI_COMMIT_REF_NAME}
    script:
        - npm config set cache $CI_PROJECT_DIR/.npm
        - npm ci
        - npm --no-git-tag-version version ${RELEASE_VERSION}
        - npm run build
        - npm publish --no-proxy
    cache:
        key: $CI_PROJECT_NAME
        paths:
            - $CI_PROJECT_DIR/.npm
    allow_failure: false
    only:
        - tags

release:
    extends: .build
    stage: build
    only:
        - tags

.build:
    tags:
        - node
    script:
        - npm config set cache $CI_PROJECT_DIR/.npm
        - npm ci
        - npm run build
    cache:
        key: $CI_PROJECT_NAME
        paths:
            - $CI_PROJECT_DIR/.npm
    allow_failure: false
